//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myClinic.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_myClinicEntities4 : DbContext
    {
        public DB_myClinicEntities4()
            : base("name=DB_myClinicEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tbl_Doctore> Tbl_Doctore { get; set; }
        public virtual DbSet<Tbl_patieont> Tbl_patieont { get; set; }
        public virtual DbSet<Tbl_section> Tbl_section { get; set; }
        public virtual DbSet<Tbl_typeLogin> Tbl_typeLogin { get; set; }
        public virtual DbSet<Tbl_visitTime> Tbl_visitTime { get; set; }
    
        public virtual ObjectResult<SP_check_Visit_Result> SP_check_Visit(Nullable<int> id_doct, string date)
        {
            var id_doctParameter = id_doct.HasValue ?
                new ObjectParameter("id_doct", id_doct) :
                new ObjectParameter("id_doct", typeof(int));
    
            var dateParameter = date != null ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_check_Visit_Result>("SP_check_Visit", id_doctParameter, dateParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_count(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_count", idParameter);
        }
    
        public virtual ObjectResult<SP_doctors_Result> SP_doctors()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_doctors_Result>("SP_doctors");
        }
    
        public virtual ObjectResult<SP_getname_doc_Result> SP_getname_doc(Nullable<int> id, Nullable<int> id_S)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var id_SParameter = id_S.HasValue ?
                new ObjectParameter("id_S", id_S) :
                new ObjectParameter("id_S", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_getname_doc_Result>("SP_getname_doc", idParameter, id_SParameter);
        }
    
        public virtual int SP_update(Nullable<int> flag, Nullable<int> id, string name, string family, string tell, string mobile, string ncood, string address, Nullable<int> filecod, string commend)
        {
            var flagParameter = flag.HasValue ?
                new ObjectParameter("flag", flag) :
                new ObjectParameter("flag", typeof(int));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var familyParameter = family != null ?
                new ObjectParameter("family", family) :
                new ObjectParameter("family", typeof(string));
    
            var tellParameter = tell != null ?
                new ObjectParameter("tell", tell) :
                new ObjectParameter("tell", typeof(string));
    
            var mobileParameter = mobile != null ?
                new ObjectParameter("mobile", mobile) :
                new ObjectParameter("mobile", typeof(string));
    
            var ncoodParameter = ncood != null ?
                new ObjectParameter("Ncood", ncood) :
                new ObjectParameter("Ncood", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var filecodParameter = filecod.HasValue ?
                new ObjectParameter("filecod", filecod) :
                new ObjectParameter("filecod", typeof(int));
    
            var commendParameter = commend != null ?
                new ObjectParameter("commend", commend) :
                new ObjectParameter("commend", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_update", flagParameter, idParameter, nameParameter, familyParameter, tellParameter, mobileParameter, ncoodParameter, addressParameter, filecodParameter, commendParameter);
        }
    
        public virtual ObjectResult<sp_view_Result> sp_view(Nullable<int> flag)
        {
            var flagParameter = flag.HasValue ?
                new ObjectParameter("flag", flag) :
                new ObjectParameter("flag", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_view_Result>("sp_view", flagParameter);
        }
    
        public virtual ObjectResult<SP_sent_Result> SP_sent(Nullable<int> id_section)
        {
            var id_sectionParameter = id_section.HasValue ?
                new ObjectParameter("id_section", id_section) :
                new ObjectParameter("id_section", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_sent_Result>("SP_sent", id_sectionParameter);
        }
    
        public virtual int SP_delete_patieont(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_delete_patieont", idParameter);
        }
    }
}
