//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myClinic.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Doctore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Doctore()
        {
            this.Tbl_visitTime = new HashSet<Tbl_visitTime>();
        }
    
        public int ID { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string cood_D { get; set; }
        public Nullable<int> ID_sec { get; set; }
        public string coment { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public byte[] imageDoc { get; set; }
    
        public virtual Tbl_section Tbl_section { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_visitTime> Tbl_visitTime { get; set; }
    }
}
