//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myClinic.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_patieont
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_patieont()
        {
            this.Tbl_visitTime = new HashSet<Tbl_visitTime>();
        }
    
        public int ID { get; set; }
        public string name { get; set; }
        public string family { get; set; }
        public string tell { get; set; }
        public string mobile { get; set; }
        public string NationalCode { get; set; }
        public string address { get; set; }
        public int FileCode { get; set; }
        public string comment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_visitTime> Tbl_visitTime { get; set; }
    }
}
